name: Auto Label

on:
  pull_request:
    types: [opened]

permissions:
  pull-requests: write
  issues: write

jobs:
  label:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@60a0d83039c74a4aee543508d2ffcb1c3799cdea # v7.0.1
        with:
          script: |
            const name = context.repo.repo.toLowerCase()
            const labels = []
            if (name.includes("lab")) labels.push("labs")
            else labels.push("core")

            await github.rest.issues.addLabels({
              ...context.repo,
              issue_number: context.issue.number,
              labels
            })
